CREATE DATABASE P336
USE P336

CREATE TABLE Students(
    Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL,
	Surname NVARCHAR(55) DEFAULT 'XXXXXX'
)


CREATE TABLE Subjects(
   Id INT PRIMARY KEY IDENTITY NOT NULL,
   [Name] NVARCHAR(50) NOT NULL,
   ExamId INT FOREIGN KEY REFERENCES Exams(Id)
)


CREATE TABLE Exams(
   Id INT PRIMARY KEY IDENTITY NOT NULL,
   [Date]  DATE 
)




CREATE TABLE StudentExams(
   Id INT PRIMARY KEY IDENTITY NOT NULL,
   StudentId INT FOREIGN KEY REFERENCES Students(Id),
   ExamId INT FOREIGN KEY REFERENCES Exams(Id),
   ExamResult INT
)

SELECT *  From Exams



